### ISSUE TITLE
Ensure poller performance before testnet 9 launch

### ISSUE THREAD

**Issue by mariocao** [stampery-labs/price_feed_poller#8]
We should make sure that the poller is working smoothly before testnet 9 launch and before a potential bridge with Ethereum mainnet.

If not yet included, the polling period should be configurable.

**Comment by girazoki** [comment]
After running the poller for 3 days in both Goerli and Rinkeby, these are the gas usage estimations we gathered:

Block Relay:

-PostNewBlock: 77223 gas units

WitnetRequestsBoard:

- claimDataRequests: 234,404 gas units
- reportDataRequestInclusion: 226087 gas units
- reportResult: 65742

Price feed:

- requestUpdate: 476245
- completeUpdate: 98920

The poller requested updates every hour, while a block was generated at Witnet every 45 seconds. To calculate what would the gas consumption be under this scenario per day, we need to assume that all blocks will be posted to Witnet. In that scenario:

- BlockRelayDailyUsage: (60*60*24/45)*PostNewBlockGasConsumption = 148272000
- PriceFeedDailyUsage: 24*(claimDataRequestsGasConsumption + reportDataRequestInclusion+reportResult+requestUpdate+completeUpdate) = 26433552

It can be observed that the major consumption comes from the fact that every block is inserted in the block relay. At current gas prices (33GW) this ends up of being a daily cost of 5.765283216 ETH.

This cost can be reduced by using superblocks instead of blocks, which are inserted, e.g., every 10 epochs. In this case we can assume the cost of storing the block headers will decrease by a factor of 10, and the overall cost would become 1361604816 ETH.
